### PR TITLE
feature/python-3.9

### PR DESCRIPTION
**Pull request by nezda**
conditionally base64.encodestring -> base64.encodebytes for python 3.9 (not sure why this got those other 2 commits - should probably also change version since 4.0.3 exists upstream now)

### CODE REVIEW

**Review by npilon — COMMENTED** [review]
We also probably want to adjust our version number to avoid upstream conflicts and be able to coherently depend on the new version.

**Comment by nezda** [comment]
> We also probably want to adjust our version number to avoid upstream conflicts and be able to coherently depend on the new version.

done @npilon https://github.com/LexMachinaInc/mailer/commit/4691c34777e68ba22e7164d64e00578882ecab8d

**Review by npilon — APPROVED** [review]
I think pip will complain about this when building the wheel, but since we're force-installing a specific wheel I'm not sure we care?

**Comment by npilon** [comment]
Especially since as noted upstream will be fixing these problems as well.

**Pull request merged**
